config/routes.rb
Rails.application.routes.draw do
root 'articles#index'

  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new'
  get '/articles/:id' => 'articles#show', as: 'articles_show'
  get '/articles/:id/edit' => 'articles#edit', as: 'articles_edit'
  put '/articles/:id' => 'articles#update', as: 'articles_update'
  delete '/articles/:id/delete' => 'articles#delete', as: 'articles_delete'
  post '/articles' => 'articles#create', as: 'articles_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
    validates :name, presence: true,
                     uniqueness: true
    validates :body, presence: true,
                     length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.valid? 
            @article.save
            flash[:notice] = "Created Successfully."
            redirect_to articles_path
        else
            render :new
        end 
    end    
    
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Updated Successfully."
            redirect_to articles_path
        else
            flash[:notice] = "Something went wrong."
            render :edit
        end
    end
    
      # DELETE /posts/1 or /posts/1.json
    def delete
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article has been deleted."
        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<div>
    <% if @article.errors.any? %>
        <h2>Could not update due to errors.</h2>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

<%= form_with scope: :article, url: articles_update_path, method: :put, local: true do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "index.css" %>
<div class="article_list">
    <% flash.each do |name,messages| %>
        <ul>
            <li><%= messages %></li>
        </ul>
    <% end %>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Body</th>
            </tr>
        </thead>

        <tbody>
            <% @articles.each do |article| %>
                <tr>
                    <td><%= article.id %></td>
                    <td><%= article.name %></td>
                    <td><%= article.body %></td>
                    <td><%= link_to 'Show', articles_show_path(article) %></td>
                    <td><%= link_to 'Edit', articles_edit_path(article) %></td>
                    <td><%= link_to 'Delete', articles_delete_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<%= link_to 'New Article', articles_new_path %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<div>
    <% if @article.errors.any? %>
        <h2>Could not create due to errors.</h2>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

<%= form_with scope: :article, url: articles_create_path, local: true do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>View Article</h1>

<p>Post ID: <%= @article.id %></p>
<p>Title: <%= @article.name %></p>
<p>Body: <%= @article.body %></p>


<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>